# Generated by Django 5.0.4 on 2024-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_bio',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
