# Generated by Django 5.0.4 on 2024-05-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cumapi', '0002_remove_customuser_user_bio_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
